{{- $fullname := include "envoy.fullname" . -}}
{{- $namespace := .Release.Namespace -}}
{{- $labels := include "envoy.labels" . -}}
{{- with .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}
  namespace: {{ $namespace }}
  labels:
    {{- $labels | nindent 4 }}
{{- toYaml . | nindent 0 }}
{{- end }}